apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app-name
  template:
    metadata:
      labels:
        app: your-app-name
    spec:
      containers:
        - name: your-app-name
          image: <your-acr-name>.azurecr.io/your-image-name:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: your-app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-name
spec:
  selector:
    app: your-app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer